language: cpp
sudo: required
before_script:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get -y install gcc-5 g++-5 libboost-system-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1  
    - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
script:
  - cmake .
  - cmake --build . -- VERBOSE=1
#  - cmake --build . --target test
  - cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T join_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uEast-Oz:$BINTRAY_API_KEY "https://api.bintray.com/content/east-oz/otus-cpp/OtusHomeworks/$TRAVIS_BUILD_NUMBER/join_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
